name: ares_defence_labs_lock_smith_pdf
description: A Flutter plugin for password-protecting PDFs with 256-bit encryption. Add a password for encryption, permissions management and decrypting a PDF
version: 0.0.1
homepage: https://github.com/Ares-Defence-Labs/Locksmith
repository: https://github.com/Ares-Defence-Labs/Locksmith

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.aresdefencelabs.locksmith_pdf
        pluginClass: LocksmithPdfPlugin
      # ios:
      #   pluginClass: LocksmithPdfPlugin

dependencies:
  flutter:
    sdk: flutter

topics:
  - pdf
  - encryption
  - security
  - password
  - android
